code organization; initial commit for gengraph

diff --git a/scripts/fuse b/scripts/fuse
--- a/scripts/fuse
+++ b/scripts/fuse
@@ -7,7 +7,7 @@ while [[ "$#" > 1 ]]; do case $1 in
     --config)     CONFIG_FUSE="$2";;
     --chunks)     CHUNKS_FUSE="$2";;
     --verbosity)  VERBOSITY_FUSE="$2";;
-    *) echo "Usage error"; exit 1;;
+    *) echo "Fuse: usage error"; exit 1;;
   esac; shift; shift
 done
 
@@ -26,6 +26,21 @@ mkdir -p $OUTPUT_FUSE
   --tracks    $TRACKS_FUSE \
   --output    $OUTPUT_FUSE/seqs.csv \
   --verbosity $VERBOSITY_FUSE
+
+if [[ $VERBOSITY_FUSE -ge 1 ]] ; then
+  echo -e "\033[1;31m"$(date)"\033[0m" "Fusion: Point Graph + Tracking"
+fi
+
+# ./modules/fuse/fuse_graph_tracking.py \
+#   --input     $OUTPUT_FUSE/seqs.csv \
+#   --output    $OUTPUT_FUSE/fused \
+#   --config    $CONFIG_FUSE \
+#   --chunks    $CHUNKS_FUSE \
+#   --verbosity $VERBOSITY_FUSE
+
+if [[ $VERBOSITY_FUSE -ge 1 ]] ; then
+  echo -e "\033[1;31m"$(date)"\033[0m" "Fusion: Generating .fuse files"
+fi
 
 ./modules/fuse/generate_fuse_files.py \
   --input     $OUTPUT_FUSE/seqs.csv \
diff --git a/scripts/postprocess b/scripts/postprocess
--- a/scripts/postprocess
+++ b/scripts/postprocess
@@ -6,12 +6,12 @@ while [[ "$#" > 1 ]]; do case $1 in
     --output)     OUTPUT_POSTPROCESS="$2";;
     --config)     CONFIG_POSTPROCESS="$2";;
     --verbosity)  VERBOSITY_POSTPROCESS="$2";;
-    *) echo "Usage error"; exit 1;;
+    *) echo "Postprocessing: usage error"; exit 1;;
   esac; shift; shift
 done
 
 if [[ $VERBOSITY_POSTPROCESS -ge 1 ]] ; then
-  echo -e "\033[1;31m"$(date)"\033[0m" "Postprocessing"
+  echo -e "\033[1;31m"$(date)"\033[0m" "Postprocessing: Stitching and Point Reduction"
 fi
 
 mkdir -p $OUTPUT_POSTPROCESS
diff --git a/scripts/preprocess b/scripts/preprocess
--- a/scripts/preprocess
+++ b/scripts/preprocess
@@ -4,12 +4,12 @@ while [[ "$#" > 1 ]]; do case $1 in
     --images)     IMAGES_PREPROCESS="$2";;
     --output)     OUTPUT_PREPROCESS="$2";;
     --config)     CONFIG_PREPROCESS="$2";;
-    --drives)     DRIVE_LIST="$2";;
+    --drives)     DRIVELIST_PREPROCESS="$2";;
     --poses)      POSES_PREPROCESS="$2";;
     --tagged)     TAGGED_PREPROCESS="$2";;
     --fuses)      FUSES_PREPROCESS="$2";;
     --verbosity)  VERBOSITY_PREPROCESS="$2";;
-    *) echo "Usage error"; exit 1;;
+    *) echo "Preprocessing: usage error"; exit 1;;
   esac; shift; shift
 done
 
@@ -25,39 +25,39 @@ mkdir -p $OUTPUT_PREPROCESS
 
 ./modules/preprocess/generate_drive_list.py \
   --images    $IMAGES_PREPROCESS \
-  --drives    $DRIVE_LIST \
+  --drives    $DRIVELIST_PREPROCESS \
   --verbosity $VERBOSITY_PREPROCESS
 
 if [[ $VERBOSITY_PREPROCESS -ge 1 ]] ; then
   echo -e "\033[1;31m"$(date)"\033[0m" "Preprocessing: Extracting detection points"
 fi
-./modules/preprocess/extract_points_from_FCN_probability_image.py \
-  --input     $IMAGES_PREPROCESS \
-  --output    $FUSES_PREPROCESS \
+./modules/preprocess/extract_points.py \
+  --images    $IMAGES_PREPROCESS \
   --poses     $POSES_PREPROCESS \
   --config    $CONFIG_PREPROCESS \
-  --drives    $DRIVE_LIST \
+  --drives    $DRIVELIST_PREPROCESS \
+  --fuses     $FUSES_PREPROCESS \
   --verbosity $VERBOSITY_PREPROCESS
 
 if [[ $VERBOSITY_PREPROCESS -ge 1 ]] ; then
   echo -e "\033[1;31m"$(date)"\033[0m" "Preprocessing: Tagging (timestamps)"
 fi
-./modules/preprocess/generate_timestamps_for_detection_points.py \
-  --input     $FUSES_PREPROCESS \
-  --output    $TAGGED_PREPROCESS \
+./modules/preprocess/tag_points.py \
+  --fuses     $FUSES_PREPROCESS \
+  --tagged    $TAGGED_PREPROCESS \
   --images    $IMAGES_PREPROCESS \
   --poses     $POSES_PREPROCESS \
   --config    $CONFIG_PREPROCESS \
-  --drives    $DRIVE_LIST \
+  --drives    $DRIVELIST_PREPROCESS \
   --verbosity $VERBOSITY_PREPROCESS
 
 if [[ $VERBOSITY_PREPROCESS -ge 1 ]] ; then
   echo -e "\033[1;31m"$(date)"\033[0m" "Preprocessing: Generating MOT"
 fi
 ./modules/preprocess/generate_MOT_data.py \
-  --input     $TAGGED_PREPROCESS \
-  --output    $OUTPUT_PREPROCESS/mot \
+  --tagged    $TAGGED_PREPROCESS \
+  --output    $OUTPUT_PREPROCESS/MOT \
   --poses     $POSES_PREPROCESS \
   --config    $CONFIG_PREPROCESS \
-  --drives    $DRIVE_LIST \
+  --drives    $DRIVELIST_PREPROCESS \
   --verbosity $VERBOSITY_PREPROCESS
diff --git a/scripts/sort b/scripts/sort
--- a/scripts/sort
+++ b/scripts/sort
@@ -5,7 +5,7 @@ while [[ "$#" > 1 ]]; do case $1 in
     --output)     OUTPUT_SORT="$2";;
 		--config)     CONFIG_SORT="$2";;
     --verbosity)  VERBOSITY_SORT="$2";;
-    *) echo "Usage error"; exit 1;;
+    *) echo "SORT: usage error"; exit 1;;
   esac; shift; shift
 done
 
diff --git a/scripts/visualize b/scripts/visualize
--- a/scripts/visualize
+++ b/scripts/visualize
@@ -6,7 +6,7 @@ while [[ "$#" > 1 ]]; do case $1 in
     --output)     OUTPUT_VISUALIZE="$2";;
     --config)     CONFIG_VISUALIZE="$2";;
     --verbosity)  VERBOSITY_VISUALIZE="$2";;
-    *) echo "Usage error"; exit 1;;
+    *) echo "Visualization: usage error"; exit 1;;
   esac; shift; shift
 done
 
