verbosity option added to sort, postprocessing and fuse

diff --git a/scripts/fuse b/scripts/fuse
--- a/scripts/fuse
+++ b/scripts/fuse
@@ -1,52 +1,41 @@
 #!/usr/bin/env bash
 
-echo -e "\033[1;31m"$(date)"\033[0m" "Fusion for EarthScape viewing"
-
-USAGE="fuse --input [dir] --tracks [dir] --output [dir] --config [json] --chunks [dir]"
 while [[ "$#" > 1 ]]; do case $1 in
-    --input)  INPUT_FUSE="$2";;
-    --tracks) TRACKS_FUSE="$2";;
-    --output) OUTPUT_FUSE="$2";;
-    --config) CONFIG_FUSE="$2";;
-    --chunks) CHUNKS_FUSE="$2";;
-    *) echo "Usage: $USAGE"; exit 1;;
+    --input)      INPUT_FUSE="$2";;
+    --tracks)     TRACKS_FUSE="$2";;
+    --output)     OUTPUT_FUSE="$2";;
+    --config)     CONFIG_FUSE="$2";;
+    --chunks)     CHUNKS_FUSE="$2";;
+    --verbosity)  VERBOSITY_FUSE="$2";;
+    *) echo "Usage error"; exit 1;;
   esac; shift; shift
 done
 
-if  [[ -z "$INPUT_FUSE"   ]] || \
-    [[ -z "$TRACKS_FUSE"  ]] || \
-    [[ -z "$OUTPUT_FUSE"  ]] || \
-    [[ -z "$CONFIG_FUSE"  ]] || \
-    [[ -z "$CHUNKS_FUSE"   ]] ; then
-  echo "Usage: $USAGE"
-  exit 1
+if [[ $VERBOSITY_FUSE -ge 1 ]] ; then
+  echo -e "\033[1;31m"$(date)"\033[0m" "Fusion for EarthScape viewing"
 fi
 
 mkdir -p $OUTPUT_FUSE
 
-./modules/fuse/print_param.py --config $CONFIG_FUSE
-
-echo $(date) >> $OUTPUT_FUSE/log.txt
-
-./modules/fuse/log_param.py \
-  --config  $CONFIG_FUSE \
-  >> $OUTPUT_FUSE/log.txt
+./modules/fuse/print_param.py \
+  --config    $CONFIG_FUSE \
+  --verbosity $VERBOSITY_FUSE
 
 ./modules/fuse/make_seq_list.py \
   --input   $INPUT_FUSE \
   --tracks  $TRACKS_FUSE \
   --output  $OUTPUT_FUSE/seqs.csv \
-  >> $OUTPUT_FUSE/log.txt
+  --verbosity $VERBOSITY_FUSE
 
 ./modules/fuse/fuse.py \
   --input   $OUTPUT_FUSE/seqs.csv \
   --output  $OUTPUT_FUSE/fused \
   --config  $CONFIG_FUSE \
   --chunks  $CHUNKS_FUSE \
-  >> $OUTPUT_FUSE/log.txt
+  --verbosity $VERBOSITY_FUSE
 
 ./modules/fuse/merge_subdrives.py \
   --input   $OUTPUT_FUSE/fused \
   --output  $OUTPUT_FUSE/fused_merged \
   --config  $CONFIG_FUSE \
-  >> $OUTPUT_FUSE/log.txt
+  --verbosity $VERBOSITY_FUSE
diff --git a/scripts/postprocess b/scripts/postprocess
--- a/scripts/postprocess
+++ b/scripts/postprocess
@@ -1,43 +1,33 @@
 #!/usr/bin/env bash
 
-echo -e "\033[1;31m"$(date)"\033[0m" "Postprocessing"
-
-USAGE="postprocess --input [dir] --tracks [dir] --output [dir] --config [json]"
 while [[ "$#" > 1 ]]; do case $1 in
-    --input)  INPUT_POSTPROCESS="$2";;
-    --tracks) TRACKS_POSTPROCESS="$2";;
-    --output) OUTPUT_POSTPROCESS="$2";;
-    --config) CONFIG_POSTPROCESS="$2";;
-    *) echo "Usage: "; exit 1;;
+    --input)      INPUT_POSTPROCESS="$2";;
+    --tracks)     TRACKS_POSTPROCESS="$2";;
+    --output)     OUTPUT_POSTPROCESS="$2";;
+    --config)     CONFIG_POSTPROCESS="$2";;
+    --verbosity)  VERBOSITY_POSTPROCESS="$2";;
+    *) echo "Usage: error"; exit 1;;
   esac; shift; shift
 done
 
-if  [[ -z "$INPUT_POSTPROCESS"  ]] || \
-    [[ -z "$TRACKS_POSTPROCESS" ]] || \
-    [[ -z "$OUTPUT_POSTPROCESS" ]] || \
-    [[ -z "$CONFIG_POSTPROCESS" ]] ; then
-  echo "Usage: $USAGE"
-  exit 1
+if [[ $VERBOSITY_POSTPROCESS -ge 1 ]] ; then
+  echo -e "\033[1;31m"$(date)"\033[0m" "Postprocessing"
 fi
 
 mkdir -p $OUTPUT_POSTPROCESS
 
-./modules/postprocess/print_param.py --config $CONFIG_POSTPROCESS
-
-echo $(date) >> $OUTPUT_POSTPROCESS/log.txt
-
-./modules/postprocess/log_param.py \
-  --config  $CONFIG_POSTPROCESS \
-  >> $OUTPUT_POSTPROCESS/log.txt
+./modules/postprocess/print_param.py \
+  --config    $CONFIG_POSTPROCESS \
+  --verbosity $VERBOSITY_POSTPROCESS
 
 ./modules/postprocess/make_seq_list.py \
   --input   $INPUT_POSTPROCESS \
   --tracks  $TRACKS_POSTPROCESS \
   --output  $OUTPUT_POSTPROCESS/seqs.csv \
-  >> $OUTPUT_POSTPROCESS/log.txt
+  --verbosity $VERBOSITY_POSTPROCESS
 
 ./modules/postprocess/postprocess.py \
   --input   $OUTPUT_POSTPROCESS/seqs.csv \
   --output  $OUTPUT_POSTPROCESS/tracks \
   --config  $CONFIG_POSTPROCESS \
-  >> $OUTPUT_POSTPROCESS/log.txt
+  --verbosity $VERBOSITY_POSTPROCESS
diff --git a/scripts/preprocess b/scripts/preprocess
--- a/scripts/preprocess
+++ b/scripts/preprocess
@@ -9,7 +9,7 @@ while [[ "$#" > 1 ]]; do case $1 in
     --tagged)     TAGGED_PREPROCESS="$2";;
     --fuses)      FUSES_PREPROCESS="$2";;
     --verbosity)  VERBOSITY_PREPROCESS="$2";;
-    *) echo "Usage: $USAGE"; exit 1;;
+    *) echo "Usage error"; exit 1;;
   esac; shift; shift
 done
 
diff --git a/scripts/sort b/scripts/sort
--- a/scripts/sort
+++ b/scripts/sort
@@ -1,35 +1,28 @@
 #!/usr/bin/env bash
 
-echo -e "\033[1;31m"$(date)"\033[0m" "Tracking: SORT"
-
-USAGE="sort --input [dir] --output [dir] --config [json]"
 while [[ "$#" > 1 ]]; do case $1 in
-    --input)  INPUT_SORT="$2";;
-    --output) OUTPUT_SORT="$2";;
-		--config) CONFIG_SORT="$2";;
-    *) echo "Usage: $USAGE"; exit 1;;
+    --input)      INPUT_SORT="$2";;
+    --output)     OUTPUT_SORT="$2";;
+		--config)     CONFIG_SORT="$2";;
+    --verbosity)  VERBOSITY_SORT="$2";;
+    *) echo "Usage error"; exit 1;;
   esac; shift; shift
 done
 
-if [[ -z "$INPUT_SORT" ]] || [[ -z "$OUTPUT_SORT" ]] || [[ -z "$CONFIG_SORT" ]] ; then
-  echo "Usage: $USAGE"
-  exit 1
+if [[ $VERBOSITY_SORT -ge 1 ]] ; then
+  echo -e "\033[1;31m"$(date)"\033[0m" "Tracking: SORT"
 fi
 
 mkdir -p $OUTPUT_SORT
 
-./modules/trackers/sort/print_param.py --config $CONFIG_SORT
-
-echo $(date) >> $OUTPUT_SORT/log.txt
-
-./modules/trackers/sort/log_param.py \
-  --config  $CONFIG_SORT \
-  >> $OUTPUT_SORT/log.txt
+./modules/trackers/sort/print_param.py \
+  --config    $CONFIG_SORT \
+  --verbosity $VERBOSITY_SORT
 
 ./modules/trackers/sort/sort.py \
   --input   $INPUT_SORT \
   --output  $OUTPUT_SORT/tracks \
   --config  $CONFIG_SORT \
-  >> $OUTPUT_SORT/log.txt
+  --verbosity $VERBOSITY_SORT
 
 
